In [ ]:
import json
import pandas as pd
import os

os.listdir('data/')

In [9]:
# Opening JSON file
event_file = open('data/events/3795506.json',)
event_json = json.load(event_file)
df = pd.read_json(event_file)
df = pd.json_normalize(event_json)
df.head()

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,foul_committed.offensive,pass.miscommunication,shot.saved_off_target,goalkeeper.shot_saved_off_target,shot.saved_to_post,goalkeeper.shot_saved_to_post,shot.open_goal,pass.cut_back,injury_stoppage.in_chain,goalkeeper.penalty_saved_to_post
0,0a58f547-aa52-4d0f-82a7-eda2a2794016,1,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a547024f-9000-4dc5-866b-fbd88b137810,2,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4c072ece-eef4-4201-a446-4d5cd8aa5d96,3,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,c0dd5679-16c3-4b99-8f04-fae3a74f0f83,4,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0aee931f-9614-4879-b3e8-fd9d7cc80c59,5,1,00:00:00.286,0,0,2,0.663637,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for i in df.columns:
    print(i)

id
index
period
timestamp
minute
second
possession
duration
type.id
type.name
possession_team.id
possession_team.name
play_pattern.id
play_pattern.name
team.id
team.name
tactics.formation
tactics.lineup
related_events
location
player.id
player.name
position.id
position.name
pass.recipient.id
pass.recipient.name
pass.length
pass.angle
pass.height.id
pass.height.name
pass.end_location
pass.type.id
pass.type.name
pass.body_part.id
pass.body_part.name
carry.end_location
under_pressure
pass.outcome.id
pass.outcome.name
ball_receipt.outcome.id
ball_receipt.outcome.name
duel.type.id
duel.type.name
pass.aerial_won
pass.deflected
counterpress
interception.outcome.id
interception.outcome.name
pass.technique.id
pass.technique.name
pass.outswinging
clearance.body_part.id
clearance.body_part.name
clearance.right_foot
pass.switch
pass.cross
pass.assisted_shot_id
pass.goal_assist
shot.statsbomb_xg
shot.end_location
shot.key_pass_id
shot.outcome.id
shot.outcome.name
shot.type.id
shot.type.name
shot.body_part.id
shot.body_part.name
shot.technique.id
shot.technique.name
shot.first_time
shot.freeze_frame
goalkeeper.outcome.id
goalkeeper.outcome.name
goalkeeper.type.id
goalkeeper.type.name
goalkeeper.position.id
goalkeeper.position.name
goalkeeper.technique.id
goalkeeper.technique.name
off_camera
dribble.outcome.id
dribble.outcome.name
duel.outcome.id
duel.outcome.name
foul_committed.type.id
foul_committed.type.name
foul_won.defensive
clearance.head
clearance.aerial_won
goalkeeper.end_location
out
pass.through_ball
ball_recovery.recovery_failure
pass.inswinging
dribble.overrun
foul_committed.advantage
foul_won.advantage
dribble.nutmeg
miscontrol.aerial_won
pass.shot_assist
pass.no_touch
clearance.left_foot
goalkeeper.body_part.id
goalkeeper.body_part.name
foul_committed.card.id
foul_committed.card.name
substitution.outcome.id
substitution.outcome.name
substitution.replacement.id
substitution.replacement.name
shot.aerial_won
shot.one_on_one
foul_committed.offensive
pass.miscommunication
shot.saved_off_target
goalkeeper.shot_saved_off_target
shot.saved_to_post
goalkeeper.shot_saved_to_post
shot.open_goal
pass.cut_back
injury_stoppage.in_chain
goalkeeper.penalty_saved_to_post

In [12]:
substitutions = df.loc[df['substitution.replacement.id'].notnull()]
substitutions

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,foul_committed.offensive,pass.miscommunication,shot.saved_off_target,goalkeeper.shot_saved_off_target,shot.saved_to_post,goalkeeper.shot_saved_to_post,shot.open_goal,pass.cut_back,injury_stoppage.in_chain,goalkeeper.penalty_saved_to_post
2211,99d61315-0208-46b4-a7e2-94ec55ccee4b,2212,2,00:08:58.002,53,58,102,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2212,c8153fdf-dcf8-430e-aac0-44cdf6109fd7,2213,2,00:09:11.376,54,11,102,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2736,1c20948f-3d40-4663-88cd-c147a9f8e974,2737,2,00:24:56.015,69,56,123,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2876,2e83136f-1488-49a2-a960-6e5d80ec7111,2877,2,00:28:25.287,73,25,127,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3273,ce6ef6b1-861c-40bf-b1cf-e204ecf143dc,3274,2,00:40:29.619,85,29,141,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
substitutions_outcome = df.loc[df['substitution.outcome.name'].notnull()]
substitutions_outcome

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,foul_committed.offensive,pass.miscommunication,shot.saved_off_target,goalkeeper.shot_saved_off_target,shot.saved_to_post,goalkeeper.shot_saved_to_post,shot.open_goal,pass.cut_back,injury_stoppage.in_chain,goalkeeper.penalty_saved_to_post
2211,99d61315-0208-46b4-a7e2-94ec55ccee4b,2212,2,00:08:58.002,53,58,102,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2212,c8153fdf-dcf8-430e-aac0-44cdf6109fd7,2213,2,00:09:11.376,54,11,102,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2736,1c20948f-3d40-4663-88cd-c147a9f8e974,2737,2,00:24:56.015,69,56,123,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2876,2e83136f-1488-49a2-a960-6e5d80ec7111,2877,2,00:28:25.287,73,25,127,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3273,ce6ef6b1-861c-40bf-b1cf-e204ecf143dc,3274,2,00:40:29.619,85,29,141,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3711,a6e5ac6e-c6f0-4236-a420-3ba141e19218,3712,3,00:00:00.000,90,0,158,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3915,ac921f60-4295-46dd-aeeb-a41fd78d3bd3,3916,3,00:05:56.382,95,56,169,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4013,1a275b3f-49ab-4194-81a6-94962765dd4a,4014,3,00:08:49.693,98,49,175,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4601,b7648b63-2ef3-49b0-a51a-e8ac18787bf2,4602,4,00:12:13.354,117,13,203,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4663,0e9b42e1-5e21-4434-a082-ed9c80bd874a,4664,4,00:14:31.836,119,31,206,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4664,8fe19205-31b8-4e5b-b156-6368187a40ff,4665,4,00:14:45.449,119,45,206,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
substitutions["substitution.outcome.name"].value_counts()

Tactical    11
Name: substitution.outcome.name, dtype: int64

In [30]:
injury_stoppage = df.loc[df["type.name"] == "Injury Stoppage"]
injury_stoppage

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,foul_committed.offensive,pass.miscommunication,shot.saved_off_target,goalkeeper.shot_saved_off_target,shot.saved_to_post,goalkeeper.shot_saved_to_post,shot.open_goal,pass.cut_back,injury_stoppage.in_chain,goalkeeper.penalty_saved_to_post
669,83c38554-ae87-4773-8f08-92dde0c9e28a,670,1,00:21:08.182,21,8,38,0.0,40,Injury Stoppage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3172,f3860002-41ef-465e-9d76-a3835a4340c2,3173,2,00:34:48.041,79,48,139,0.0,40,Injury Stoppage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3315,a735f306-776b-4ea1-8299-646dfefa9352,3316,2,00:41:28.430,86,28,143,0.0,40,Injury Stoppage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3316,e483112f-2f5e-4380-9db9-f630677479e1,3317,2,00:41:28.962,86,28,143,0.0,40,Injury Stoppage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
4516,d6db119e-ac2f-4ca8-bd04-eae28bd86a8e,4517,4,00:07:32.028,112,32,200,0.0,40,Injury Stoppage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
injury_stoppage.shape

(5, 122)

In [31]:
substitutions.shape

(11, 122)

In [40]:
# See all data
import os
event_data_path = "data/events/"
event_files = os.listdir(event_data_path)
count = 0
dfs = [] # an empty list to store the data frames
for event_file in event_files:
    count += 1
    # data = pd.read_json(file, lines=True) # read data frame from json file
    event_file = open(event_data_path + event_file,encoding='UTF-8')
    data = json.load(event_file)
    # data = pd.read_json(event_data_path + event_file, lines=True)
    df = pd.json_normalize(data)
    substitutions_outcome = df.loc[df['substitution.outcome.name'].notnull()]
    dfs.append(substitutions_outcome) # append the data frame to the list

all_subs_data = pd.concat(dfs, ignore_index=True) # concatenate all the data frames in the list.

In [41]:
all_subs_data.shape

(5364, 149)

In [86]:
injury_subs_data = all_subs_data.loc[all_subs_data['substitution.outcome.name'] == "Injury"]

In [87]:
injury_subs_data.shape

(296, 149)

In [81]:
# Get potential injury substitutions
import warnings
warnings.filterwarnings("ignore")
event_data_path = "data/events/"
event_files = os.listdir(event_data_path)
count = 0
injury_df = [] # an empty list to store the data frames
for event_file in event_files:
    count += 1
    # data = pd.read_json(file, lines=True) # read data frame from json file
    event_file = open(event_data_path + event_file,encoding='UTF-8')
    data = json.load(event_file)
    # data = pd.read_json(event_data_path + event_file, lines=True)
    df = pd.json_normalize(data)

    tactical_substitutions = df.loc[df['substitution.outcome.name'] == 'Tactical']
    injury_stoppage = df.loc[df["type.name"] == "Injury Stoppage"]
    injury_stoppage_mergedf = injury_stoppage[["player.name", "minute"]]
    injury_stoppage_mergedf.rename(columns={"minute": "minute_y"}, inplace=True)
    injury_stoppage_mergedf["injury_limit"] = injury_stoppage_mergedf["minute_y"] + 10
    injury_stoppage_mergedf
    new_df = pd.merge(tactical_substitutions, injury_stoppage_mergedf,  how='inner', left_on=['player.name'], right_on = ['player.name'])
    new_df = new_df[(new_df["minute"] <= new_df["injury_limit"]) & (new_df["minute"] >= new_df["minute_y"])]
    injury_df.append(new_df)

possible_injury_subs_data = pd.concat(injury_df, ignore_index=True) # concatenate all the data frames in the list.

In [84]:
possible_injury_subs_data[["minute", "minute_y","injury_limit"]]

     minute  minute_y  injury_limit
0        62        54            64
1        86        78            88
2        45        45            55
3        45        36            46
4        76        74            84
..      ...       ...           ...
152      71        71            81
153      60        56            66
154      65        56            66
155       9         9            19
156      45        45            55

[157 rows x 3 columns]

In [85]:
possible_injury_subs_data_merge = possible_injury_subs_data.drop(["minute_y","injury_limit"], axis = 1)
possible_injury_subs_data_merge.shape

(157, 149)

In [88]:
# Concatenate all injuries
all_injuries = pd.concat([possible_injury_subs_data_merge, injury_subs_data], ignore_index=True, sort=False)
all_injuries

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,goalkeeper.shot_saved_to_post,goalkeeper.lost_out,player_off.permanent,goalkeeper.lost_in_play,goalkeeper.success_out,goalkeeper.success_in_play,goalkeeper.saved_to_post,half_end.early_video_end,shot.kick_off,goalkeeper.penalty_saved_to_post
0,e9aedc0e-afea-42d3-bcfc-5fd744e9d9ed,2685,2,00:17:55.394,62,55,109,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a6f430d6-a5e5-4317-b55a-e1cadd0afc7f,3702,2,00:41:53.704,86,53,164,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,222c0a40-bc5f-4649-baad-86764a371613,1982,2,00:00:00.000,45,0,84,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f64673c4-2315-4a8c-b128-6d990076c97e,1937,2,00:00:00.000,45,0,118,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29f59450-bde4-4202-9f17-165623ad3c82,3279,2,00:31:37.192,76,37,191,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,b78a7b2b-4ddf-4bba-b2ef-f00f137aaf96,2005,1,00:38:38.333,38,38,59,NaN,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,9acde55c-2529-4280-bd37-dcf356ada57b,3467,2,00:26:33.879,71,33,147,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,a850a657-efef-4db1-b94f-66e7fbdd051c,2305,2,00:09:42.206,54,42,113,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,7517d55d-9515-497a-ac5e-742e3b3e1bad,1746,1,00:42:40.556,42,40,81,0.00,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452,594b5330-96df-4777-b5a7-18fd4b411b59,2117,2,00:00:00.000,45,0,87,5.28,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
all_injuries.sort_values(by=['period','timestamp'], inplace=True)
all_injuries = all_injuries.reset_index(drop=True)

In [96]:
all_injuries

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,goalkeeper.shot_saved_to_post,goalkeeper.lost_out,player_off.permanent,goalkeeper.lost_in_play,goalkeeper.success_out,goalkeeper.success_in_play,goalkeeper.saved_to_post,half_end.early_video_end,shot.kick_off,goalkeeper.penalty_saved_to_post
0,3bfeae61-a48f-4457-9332-863aa052e736,205,1,00:05:09.644,5,9,9,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,971625c8-8ac8-4237-89ea-ce19a778b3fc,400,1,00:07:03.086,7,3,15,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a069271e-6663-4e38-979c-ad3190461efb,450,1,00:07:54.916,7,54,14,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6a81bfc2-1e54-4dcc-b0e0-ca6933835988,452,1,00:08:55.233,8,55,21,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c322970d-5e87-4fa8-8afb-9640bc0bfb59,348,1,00:09:08.005,9,8,19,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,5281b6fd-2f82-47bf-9341-205ae91dcdfc,3736,3,00:06:13.769,96,13,215,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,1a23ade2-e25b-4652-afbf-3e6326efdcdc,4138,3,00:10:02.218,100,2,145,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,f0d41245-a4f1-4fa9-84df-d1bd6972983d,4139,3,00:10:38.468,100,38,145,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,0c843e61-31a6-447f-9ede-430f86b10edc,3916,4,00:09:51.803,114,51,234,NaN,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452,ad75dcad-2861-411a-bffe-dd20dddfabd6,3534,4,00:12:50.618,117,50,274,0.0,19,Substitution,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
all_injuries.to_csv('all_injuries.csv', index = False, header=True)

In [100]:
# possible_injury_subs_data[possible_injury_subs_data["id"] == "63919dae-7c0b-4ffd-aedf-dbb7ed4be7de"][["minute", "minute_y"]]

     minute  minute_y
155       9         9