In [5]:
import pandas as pd
import random

In [2]:
data = pd.read_csv('./TableauData/all.csv')
data.head()

/Users/tyler/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (17,37,43,45,50,55,60,79,82,84,86,88,89,90,95,96,97,98,99,100,101,102,103,104,106,107,108,113,114,115,116,118,119,120,121,122,123,124,125,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,half_start.late_video_start,goalkeeper.success_in_play,goalkeeper.success_out,shot.follows_dribble,goalkeeper.lost_out,goalkeeper.penalty_saved_to_post,goalkeeper.saved_to_post,half_end.early_video_end,player_off.permanent,shot.kick_off
0,91fdaa62-e36b-4aca-8c56-7a6d32289483,1,1,00:00:00.000,0,0,1,0.00000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aae12223-7969-4f4e-ac4e-83b075af1352,2,1,00:00:00.000,0,0,1,0.00000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ba7b6ef4-edab-43e9-8ed2-ccc073667b8f,3,1,00:00:00.000,0,0,1,0.00000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f8f30929-e011-4ea9-bbc9-c22873023d5f,4,1,00:00:00.000,0,0,1,0.00000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c0927b64-b182-4e44-83f0-b77222d600f8,5,1,00:00:00.443,0,0,2,0.85577,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,half_start.late_video_start,goalkeeper.success_in_play,goalkeeper.success_out,shot.follows_dribble,goalkeeper.lost_out,goalkeeper.penalty_saved_to_post,goalkeeper.saved_to_post,half_end.early_video_end,player_off.permanent,shot.kick_off
0,91fdaa62-e36b-4aca-8c56-7a6d32289483,1,1,00:00:00.000,0,0,1,0.00000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aae12223-7969-4f4e-ac4e-83b075af1352,2,1,00:00:00.000,0,0,1,0.00000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ba7b6ef4-edab-43e9-8ed2-ccc073667b8f,3,1,00:00:00.000,0,0,1,0.00000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f8f30929-e011-4ea9-bbc9-c22873023d5f,4,1,00:00:00.000,0,0,1,0.00000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c0927b64-b182-4e44-83f0-b77222d600f8,5,1,00:00:00.443,0,0,2,0.85577,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3792072,a2becaf4-d3e5-4bf3-9459-0b442020b72a,4986,5,00:05:54.582,125,54,237,0.00000,23,Goal Keeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3792073,a6217adf-c93a-4229-8ea9-f1a58752ca34,4987,5,00:07:04.301,127,4,238,0.56802,16,Shot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3792074,aa15567a-333d-4aca-9df0-173672564d43,4988,5,00:07:04.869,127,4,238,0.00000,23,Goal Keeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3792075,abefbcd4-a519-4879-9a28-cc09552141fc,4989,5,00:07:05.592,127,5,238,0.00000,34,Half End,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3792076,7be5fa66-8c67-40d6-8697-996775eb7ec2,4990,5,00:07:05.592,127,5,238,0.00000,34,Half End,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data.iloc[[1, 4]]

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,half_start.late_video_start,goalkeeper.success_in_play,goalkeeper.success_out,shot.follows_dribble,goalkeeper.lost_out,goalkeeper.penalty_saved_to_post,goalkeeper.saved_to_post,half_end.early_video_end,player_off.permanent,shot.kick_off
1,aae12223-7969-4f4e-ac4e-83b075af1352,2,1,00:00:00.000,0,0,1,0.00000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c0927b64-b182-4e44-83f0-b77222d600f8,5,1,00:00:00.443,0,0,2,0.85577,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
rand_idxs = random.sample(range(data.shape[0]), 20000)
rand_idxs

[1564084,
 2100088,
 3339276,
 3032379,
 3156939,
 2170295,
 933093,
 703060,
 968056,
 2434237,
 3543803,
 3779145,
 583068,
 3367221,
 387622,
 304829,
 2828168,
 2397624,
 474812,
 1509222,
 878908,
 2687026,
 2180908,
 2677135,
 3158644,
 3566021,
 1360248,
 308251,
 3507972,
 1144657,
 327402,
 1842259,
 2587722,
 3638245,
 3268734,
 2258343,
 2840604,
 206716,
 752727,
 3265030,
 1932101,
 2946927,
 2724974,
 2063359,
 90822,
 1141385,
 1258615,
 1539899,
 298799,
 3494344,
 574972,
 273924,
 203658,
 1168849,
 1368345,
 3108623,
 2273453,
 2170307,
 1844171,
 3490305,
 2161165,
 1166088,
 104189,
 578823,
 1169057,
 960777,
 2949160,
 1390095,
 1856246,
 2610622,
 3565713,
 80579,
 747041,
 2638302,
 3565581,
 816345,
 1858431,
 855823,
 2948564,
 2978926,
 3781896,
 2625617,
 1193401,
 2083782,
 2146207,
 1156825,
 2554752,
 28026,
 690253,
 535622,
 2078775,
 3761426,
 2607735,
 406972,
 626906,
 659315,
 2213458,
 1338448,
 1158030,
 1542085,
 1022370,
 619417,
 807622,
 3688237,
 3595002,
 1787576,
 1049481,
 3256521,
 200123,
 1493622,
 2842705,
 2491852,
 1448864,
 3243982,
 1117696,
 1750938,
 2376418,
 2304877,
 1363643,
 41672,
 2961630,
 643652,
 239050,
 543621,
 450513,
 3243066,
 3054710,
 1225673,
 2626780,
 2339993,
 2430299,
 313584,
 2312414,
 1987880,
 1456040,
 1231798,
 411907,
 3571039,
 3635462,
 1236053,
 3655131,
 2185085,
 1095672,
 3554480,
 3131798,
 3433047,
 3707012,
 1381881,
 1860789,
 1525064,
 1859350,
 213824,
 3205951,
 1481442,
 1978266,
 1600134,
 1817508,
 1724917,
 56128,
 1080614,
 2925744,
 1097949,
 3468496,
 1904580,
 571885,
 1739146,
 3370368,
 865201,
 762299,
 662692,
 3789730,
 1930222,
 3658847,
 3683628,
 2419371,
 1095275,
 14293,
 2633051,
 372477,
 603173,
 161964,
 1293041,
 3041321,
 3185599,
 3245397,
 730897,
 2750807,
 205687,
 2886785,
 1659382,
 2215354,
 2319479,
 475987,
 1830986,
 3550099,
 1645458,
 3378366,
 3279555,
 1707700,
 409355,
 1548380,
 721703,
 2703999,
 1131335,
 3080464,
 758179,
 3426604,
 2509876,
 289075,
 1070815,
 3292199,
 1095454,
 850561,
 498513,
 165497,
 1824432,
 2528104,
 1755919,
 157280,
 3257572,
 1683965,
 1717037,
 3683337,
 498492,
 2600920,
 27800,
 3078957,
 2696504,
 355999,
 1416874,
 2022967,
 1457538,
 732020,
 2870354,
 3715012,
 2194319,
 2963330,
 857653,
 1909513,
 2558126,
 125287,
 770588,
 2548418,
 2106434,
 1894513,
 516604,
 3087541,
 1610212,
 3345753,
 1489178,
 3761145,
 2545485,
 344943,
 591755,
 362926,
 3719285,
 1708798,
 391852,
 1766082,
 2492270,
 3441191,
 3747868,
 946659,
 3610339,
 2758325,
 1581785,
 3513381,
 1742261,
 2187282,
 492636,
 2232163,
 196243,
 180279,
 334504,
 2804648,
 764081,
 3695864,
 1015354,
 591088,
 2047115,
 2746626,
 3368402,
 3109399,
 3669021,
 2531734,
 3430621,
 14561,
 592018,
 683888,
 3531423,
 1829318,
 575055,
 2268764,
 1074860,
 2728804,
 168550,
 2629452,
 1510500,
 2817026,
 1322608,
 2691443,
 255914,
 10803,
 2534881,
 2938828,
 2663117,
 648895,
 1468197,
 458916,
 2739243,
 47805,
 1060845,
 3506137,
 238469,
 3007196,
 2032264,
 3765364,
 1023598,
 3115983,
 3676504,
 321385,
 797190,
 477197,
 1875422,
 183629,
 2520597,
 396024,
 1672405,
 743422,
 2995464,
 2316620,
 2828150,
 2199450,
 901548,
 1180489,
 284381,
 2127902,
 1609973,
 2229579,
 394409,
 2715497,
 1944212,
 2853265,
 2812920,
 1361069,
 2033868,
 2342014,
 3110876,
 365540,
 90950,
 1307509,
 1859136,
 3431508,
 616734,
 1013417,
 1975110,
 1990274,
 2449265,
 1810731,
 852914,
 3548436,
 813326,
 973488,
 95935,
 1682160,
 133425,
 3456631,
 1121726,
 2204020,
 2027291,
 2320351,
 3018015,
 1234686,
 46698,
 897825,
 3018364,
 2823700,
 2972411,
 3221403,
 2398126,
 3016237,
 1944978,
 1645529,
 1692157,
 2114609,
 1560512,
 934793,
 2981216,
 92793,
 2374131,
 2901395,
 2063957,
 3527166,
 959181,
 3110379,
 1099107,
 1766235,
 3741435,
 1953082,
 2559089,
 1019530,
 600678,
 605920,
 660800,
 77601,
 1251624,
 3697904,
 2177481,
 3044786,
 1126873,
 919925,
 745868,
 1926291,
 2209262,
 1658964,
 2429680,
 359747,
 3614279,
 832812,
 2935955,
 1726887,
 2608090,
 3762014,
 2051048,
 2202956,
 1380331,
 905873,
 2252408,
 3626729,
 1058720,
 1698514,
 779330,
 881845,
 1060437,
 19839,
 3563661,
 2953545,
 3384774,
 887597,
 831084,
 1786423,
 898825,
 2905715,
 2730273,
 2586261,
 2731757,
 2551093,
 530314,
 673975,
 3340391,
 3081584,
 2406423,
 1016027,
 3449238,
 539287,
 1719995,
 1325877,
 429849,
 3339485,
 94228,
 2010594,
 370566,
 1307946,
 3646003,
 3542099,
 1069104,
 2351733,
 658730,
 978751,
 2929200,
 2005329,
 2479841,
 3604689,
 3348857,
 1268929,
 798124,
 2748816,
 1323475,
 1979018,
 2464267,
 2168467,
 2409111,
 359773,
 2710250,
 2425443,
 568319,
 3151557,
 402953,
 515991,
 2881214,
 3699832,
 2258252,
 277613,
 2167765,
 3721141,
 1680926,
 672500,
 1831757,
 888255,
 1822964,
 912366,
 706957,
 370800,
 656592,
 879116,
 2936609,
 1832146,
 1639057,
 511868,
 2767591,
 2273754,
 1615420,
 3066447,
 3546716,
 118575,
 163228,
 1649248,
 2700898,
 915843,
 3607343,
 1613598,
 2315978,
 256854,
 2370933,
 2281927,
 2060351,
 2472529,
 496419,
 3470817,
 1951,
 3418210,
 1249274,
 354601,
 2075026,
 1703561,
 3132309,
 728203,
 891419,
 3504135,
 2114772,
 798377,
 3411983,
 516654,
 1062136,
 3754727,
 1791415,
 2518878,
 1386786,
 265461,
 1508804,
 501200,
 1325438,
 311015,
 2704471,
 1365346,
 411340,
 2292893,
 3089787,
 2521595,
 3067791,
 450570,
 1318594,
 3459672,
 3434340,
 1881821,
 3286389,
 107919,
 2173605,
 1342997,
 2751009,
 54402,
 2638672,
 3561975,
 3185838,
 1421814,
 1956960,
 2185027,
 2687226,
 1124034,
 1840225,
 946047,
 16826,
 1128018,
 3367776,
 2703526,
 608181,
 2678813,
 2434751,
 1010370,
 101132,
 3408455,
 2154370,
 3125139,
 2512747,
 2176250,
 466851,
 2275845,
 2241460,
 1940402,
 67092,
 333789,
 3337988,
 1296278,
 510917,
 3692692,
 3249384,
 3246259,
 1260119,
 2001096,
 1254763,
 2743803,
 819556,
 682245,
 741905,
 888118,
 2780269,
 2936866,
 3656742,
 1761050,
 1774387,
 1933002,
 3627869,
 2352651,
 556170,
 1553776,
 590111,
 3191993,
 896539,
 3201885,
 3631504,
 307524,
 2683060,
 2553964,
 1426384,
 1285555,
 2929756,
 944693,
 2338263,
 1112828,
 3361582,
 2129304,
 1050175,
 619682,
 747373,
 1429178,
 2715824,
 3758139,
 1051435,
 3626838,
 1660051,
 109949,
 3613801,
 550650,
 1127900,
 544108,
 2347039,
 3108371,
 1658208,
 3457089,
 2776961,
 2136518,
 3274697,
 2497587,
 1484678,
 313029,
 1307030,
 2878794,
 48722,
 2814054,
 2522588,
 2009238,
 2018228,
 2027881,
 2701452,
 2439559,
 2451729,
 1446149,
 3227734,
 696214,
 3335459,
 3482721,
 453821,
 538792,
 893815,
 3317633,
 2828557,
 2158382,
 502472,
 1419282,
 248752,
 39056,
 787699,
 748063,
 2410204,
 3769144,
 603082,
 2410951,
 1137637,
 3068697,
 3641384,
 365137,
 1456086,
 1229507,
 809346,
 39723,
 1050845,
 3754852,
 1086561,
 3456756,
 3418220,
 1210198,
 856415,
 3438500,
 445839,
 1327171,
 2705651,
 966711,
 666358,
 1222557,
 1689505,
 812650,
 101522,
 1271507,
 744994,
 882950,
 3338277,
 2508300,
 2193149,
 2404138,
 3489360,
 1628141,
 301354,
 2923751,
 2289876,
 1343426,
 2540851,
 1547831,
 3695074,
 2040966,
 1238904,
 1604188,
 3357142,
 413258,
 817074,
 384202,
 717579,
 3730432,
 1334533,
 3732253,
 40966,
 2270252,
 995049,
 1617961,
 194442,
 221938,
 1706895,
 557986,
 1217372,
 1202229,
 3430388,
 712797,
 588487,
 1570875,
 806448,
 2477129,
 468543,
 825606,
 2668342,
 3735346,
 1752767,
 2621949,
 1722715,
 3510526,
 3244619,
 3026151,
 3692933,
 3512193,
 1773387,
 1958039,
 879967,
 3357103,
 304885,
 2945224,
 2507489,
 2256614,
 1384212,
 3212386,
 2727585,
 1655198,
 2679009,
 2128214,
 2420055,
 3338122,
 940135,
 2209394,
 2289429,
 3443438,
 718917,
 1715486,
 934484,
 2296363,
 2946321,
 3166920,
 2884579,
 2355750,
 2766,
 323243,
 2298354,
 1720506,
 2988144,
 1530356,
 589841,
 2242232,
 2871743,
 2650988,
 3791370,
 3664936,
 3537446,
 2448120,
 424885,
 3477625,
 374457,
 3547083,
 1792768,
 2939548,
 151808,
 3282025,
 696505,
 888926,
 2514670,
 844587,
 1369692,
 349986,
 1119711,
 769643,
 2620443,
 2360237,
 2401055,
 2854383,
 846839,
 2780995,
 2345074,
 2532031,
 3015485,
 1441958,
 52377,
 1039555,
 1397513,
 2858391,
 304345,
 913823,
 3610845,
 2498266,
 3711826,
 3159907,
 1892883,
 1398142,
 1222858,
 2816994,
 3130871,
 3379451,
 561050,
 3090291,
 1703915,
 502060,
 628655,
 3303023,
 1366064,
 539881,
 1877560,
 276653,
 3707629,
 265764,
 165399,
 1866294,
 2903179,
 1260923,
 655959,
 3712477,
 2761023,
 2458386,
 161523,
 2061207,
 1745460,
 1935018,
 1203140,
 3228906,
 2302106,
 2942269,
 1822189,
 626654,
 3200146,
 2123188,
 3030878,
 1311589,
 192107,
 3182798,
 1699882,
 2052751,
 287386,
 3254998,
 3790373,
 1215656,
 1824489,
 2949719,
 1765852,
 2851785,
 2548109,
 2092285,
 280271,
 2418523,
 1301614,
 3175083,
 26365,
 3493777,
 1264345,
 1557684,
 517691,
 308300,
 3724805,
 2915291,
 2360860,
 1935503,
 3005822,
 1940346,
 2070921,
 2000730,
 3690185,
 3786696,
 329285,
 1906853,
 3769983,
 110291,
 734024,
 960388,
 933468,
 3412800,
 400806,
 2439195,
 2694461,
 2586336,
 664616,
 1031294,
 3662152,
 3304129,
 3413154,
 2746890,
 2723145,
 3497932,
 1760198,
 723980,
 812735,
 243407,
 770456,
 1978427,
 2259293,
 2253570,
 2620681,
 1381101,
 2080686,
 3708257,
 915500,
 2716142,
 3463896,
 2427689,
 167839,
 2814846,
 2379185,
 414299,
 2359206,
 2778207,
 1370383,
 2578334,
 1706706,
 1576842,
 2312892,
 1872666,
 2920163,
 829992,
 1770931,
 570416,
 2744414,
 3022,
 107816,
 1457723,
 140191,
 106296,
 3052756,
 1450252,
 1904335,
 1449461,
 1109912,
 3407968,
 2086414,
 3190415,
 732762,
 147554,
 1307483,
 2925625,
 880921,
 ...]

In [15]:
toy_data = data.iloc[rand_idxs]
toy_data.shape

(20000, 150)

In [16]:
toy_data.to_csv('./toy.csv')